projects:
  app:
    schemaPath: src/schema.graphql
    includes: ["**/*.graphql"]
    extensions:
      endpoints:
        default: http://localhost:4000
  db:
    schemaPath: prisma/datamodel.prisma
    includes: ["**/*.prisma"]
    extensions:
      codegen:
      - generator: graphql-binding
        language: javascript
        output:
          binding: src/generated/prisma-client/index.d.ts